/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Relacional;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author DANIEL
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.setLocationRelativeTo(null);
        EntidadesTexto.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonsalir = new javax.swing.JButton();
        ent = new javax.swing.JTextField();
        atribsimples = new javax.swing.JTextField();
        atribmulti = new javax.swing.JTextField();
        atribcompuesto = new javax.swing.JTextField();
        ingresarent = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        relac = new javax.swing.JTextField();
        atrib = new javax.swing.JTextField();
        ents = new javax.swing.JTextField();
        part = new javax.swing.JTextField();
        card = new javax.swing.JTextField();
        ingresarrela = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        entcom = new javax.swing.JTextField();
        entorig = new javax.swing.JTextField();
        atribentcom = new javax.swing.JTextField();
        tipo = new javax.swing.JTextField();
        ingresarentcom = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        EntidadesTexto = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        tipodentidad = new javax.swing.JTextField();
        llaveprimaria = new javax.swing.JTextField();
        tipoent2 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        tiporelrelacion = new javax.swing.JTextField();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonsalir.setBackground(new java.awt.Color(102, 102, 102));
        botonsalir.setText("Salir");
        botonsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonsalirActionPerformed(evt);
            }
        });
        getContentPane().add(botonsalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 0, -1, -1));

        ent.setBackground(new java.awt.Color(102, 102, 102));
        ent.setForeground(new java.awt.Color(0, 0, 153));
        getContentPane().add(ent, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 70, -1));

        atribsimples.setBackground(new java.awt.Color(102, 102, 102));
        atribsimples.setForeground(new java.awt.Color(0, 0, 102));
        getContentPane().add(atribsimples, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 70, -1));

        atribmulti.setBackground(new java.awt.Color(102, 102, 102));
        atribmulti.setForeground(new java.awt.Color(0, 0, 102));
        atribmulti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atribmultiActionPerformed(evt);
            }
        });
        getContentPane().add(atribmulti, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, 70, -1));

        atribcompuesto.setBackground(new java.awt.Color(102, 102, 102));
        atribcompuesto.setForeground(new java.awt.Color(0, 0, 102));
        getContentPane().add(atribcompuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, 70, -1));

        ingresarent.setText("Ingresar");
        ingresarent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresarentActionPerformed(evt);
            }
        });
        getContentPane().add(ingresarent, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 90, -1, -1));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("    Entidad          Llave Primaria    Atrib. Simple         Atrib.Multi          Atrib.Comp        Tipo Entidad");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 530, -1));

        relac.setBackground(new java.awt.Color(102, 102, 102));
        relac.setForeground(new java.awt.Color(0, 0, 102));
        getContentPane().add(relac, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 70, -1));

        atrib.setBackground(new java.awt.Color(102, 102, 102));
        atrib.setForeground(new java.awt.Color(0, 0, 102));
        getContentPane().add(atrib, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 70, -1));

        ents.setBackground(new java.awt.Color(102, 102, 102));
        ents.setForeground(new java.awt.Color(0, 0, 102));
        getContentPane().add(ents, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 70, -1));

        part.setBackground(new java.awt.Color(102, 102, 102));
        part.setForeground(new java.awt.Color(0, 0, 102));
        getContentPane().add(part, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, 70, -1));

        card.setBackground(new java.awt.Color(102, 102, 102));
        card.setForeground(new java.awt.Color(0, 0, 102));
        getContentPane().add(card, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 230, 70, -1));

        ingresarrela.setText("ingresar");
        ingresarrela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresarrelaActionPerformed(evt);
            }
        });
        getContentPane().add(ingresarrela, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 230, -1, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("   Relación             Atributos            Entidades         Participacion     Cardinalidad    Tipo de Relacion");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 550, -1));

        entcom.setBackground(new java.awt.Color(102, 102, 102));
        entcom.setForeground(new java.awt.Color(0, 0, 102));
        getContentPane().add(entcom, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 70, -1));

        entorig.setBackground(new java.awt.Color(102, 102, 102));
        entorig.setForeground(new java.awt.Color(0, 0, 102));
        getContentPane().add(entorig, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 70, -1));

        atribentcom.setBackground(new java.awt.Color(102, 102, 102));
        atribentcom.setForeground(new java.awt.Color(0, 0, 102));
        getContentPane().add(atribentcom, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 70, -1));

        tipo.setBackground(new java.awt.Color(102, 102, 102));
        tipo.setForeground(new java.awt.Color(0, 0, 102));
        getContentPane().add(tipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, 70, -1));

        ingresarentcom.setText("ingresar");
        ingresarentcom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresarentcomActionPerformed(evt);
            }
        });
        getContentPane().add(ingresarentcom, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 160, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText(" Entidad Hija      Entidad Padre        Atributos                 Tipo                Tipo Entidad");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        EntidadesTexto.setBackground(new java.awt.Color(102, 102, 102));
        EntidadesTexto.setColumns(20);
        EntidadesTexto.setForeground(new java.awt.Color(0, 0, 102));
        EntidadesTexto.setRows(5);
        jScrollPane1.setViewportView(EntidadesTexto);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 440, 220));

        jButton1.setBackground(new java.awt.Color(102, 102, 102));
        jButton1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 51, 51));
        jButton1.setText("Transformar ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 320, 210, 50));

        jLabel4.setFont(new java.awt.Font("Consolas", 1, 22)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Convertir de Modelo Entidad-Relación a Modelo Relacional");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, -1));

        tipodentidad.setBackground(new java.awt.Color(102, 102, 102));
        tipodentidad.setForeground(new java.awt.Color(0, 0, 102));
        getContentPane().add(tipodentidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 90, 70, -1));

        llaveprimaria.setBackground(new java.awt.Color(102, 102, 102));
        llaveprimaria.setForeground(new java.awt.Color(0, 0, 102));
        getContentPane().add(llaveprimaria, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 70, -1));

        tipoent2.setBackground(new java.awt.Color(102, 102, 102));
        tipoent2.setForeground(new java.awt.Color(0, 0, 102));
        getContentPane().add(tipoent2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, 70, -1));

        jButton3.setBackground(new java.awt.Color(102, 102, 102));
        jButton3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(51, 51, 51));
        jButton3.setText("Limpiar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 410, -1, -1));

        jLabel5.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("·Victor Daniel Bohórquez Toribio        ·Brandon Ivan Hernández Reséndiz");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 560, -1, -1));

        tiporelrelacion.setBackground(new java.awt.Color(102, 102, 102));
        tiporelrelacion.setForeground(new java.awt.Color(0, 0, 102));
        tiporelrelacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tiporelrelacionActionPerformed(evt);
            }
        });
        getContentPane().add(tiporelrelacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 230, 70, -1));

        fondo.setFont(new java.awt.Font("Consolas", 1, 36)); // NOI18N
        fondo.setForeground(new java.awt.Color(204, 0, 0));
        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fon.jpg"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonsalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_botonsalirActionPerformed

    private void atribmultiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atribmultiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_atribmultiActionPerformed

    private void ingresarentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresarentActionPerformed
        String nombreentidad="";
        nombreentidad=ent.getText();
        String llavesprimarias="";
        llavesprimarias=llaveprimaria.getText();
        String atribsimple="";
        atribsimple=atribsimples.getText();
        String atribtmulti="";
        atribtmulti=atribmulti.getText();
        String atribcom="";
        atribcom=atribcompuesto.getText();
        String tipoent="";
        tipoent=tipodentidad.getText();
        ArrayList<String> llp;
        ArrayList<String> as=new ArrayList<String>();
        ArrayList<String> am=new ArrayList<String>();
        ArrayList<String> acom=new ArrayList<String>();
        ArrayList<ArrayList<String>> acomf= new ArrayList<ArrayList<String>>();
        String cuadro="";
        if(nombreentidad.equals("") || llavesprimarias.equals("") || tipoent.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Necesitas llenar los campos minimos", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        else
        {
           llp=separador.separarllavespyatrib(llavesprimarias);  
           if(!atribsimple.equals("")){
           as=separador.separarllavespyatrib(atribsimple);
           }
           if(!atribtmulti.equals("")){
           am=separador.separarllavespyatrib(atribtmulti);
           }
           if(!atribcom.equals("")){
           acom=separador.separaratribcompuestos(atribcom);
           for (int i=0;i<acom.size();i++)
           {
               acomf.add(separador.separarllavespyatrib(acom.get(i)));
           }
           }
           Entidad e= new Entidad(nombreentidad,tipoent);
           e.añadirllavesp(llp);
           if(!as.isEmpty()){e.añadirsimples(as);}
           if(!am.isEmpty()){e.añadirmultiv(am);}
           if(!acomf.isEmpty()){e.añadircompuestos(acomf);}
           entidades.add(e);
           entidades2.add(e);
           cuadro=e.getnombre()+"= "+ e.getllaves()+e.getatributos()+"\n";
        }
        
        ent.setText("");
        llaveprimaria.setText("");
        atribsimples.setText("");
        atribmulti.setText("");
        atribcompuesto.setText("");
        tipodentidad.setText("");
        textocuadro1 += cuadro;
        EntidadesTexto.setText(textocuadro1);
    }//GEN-LAST:event_ingresarentActionPerformed

    private void ingresarrelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresarrelaActionPerformed
        String nombrerelacion="";
        nombrerelacion=relac.getText();
        String entidads="";
        entidads=ents.getText();
        String atribs="";
        atribs=atrib.getText();
        String parti="";
        parti=part.getText();
        String cardi="";
        cardi=card.getText();
        String tre="";
        tre=tiporelrelacion.getText();       
        ArrayList<String> en;
        ArrayList<String> a= new ArrayList<String>();
        ArrayList<Entidad> en2= new ArrayList<Entidad>();
        String cuadro="";
        if(nombrerelacion.equals("") || entidads.equals("") || parti.equals("")|| cardi.equals("") || tre.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Necesitas llenar todos los campos minimos", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        else
        {
           en=separador.separarllavespyatrib(entidads);
           if(!atribs.equals("")){
           a=separador.separarllavespyatrib(atribs);
           }
           for(int x=0;x<en.size();x++)
           {
           for (int i=0;i<entidades.size();i++)
           {
               if(((entidades.get(i)).getnombre()).equals(en.get(x)))
               {
                   en2.add(entidades.get(i));
               }
           }
           }
           Relacion r= new Relacion(nombrerelacion,parti,cardi);
           if(!a.isEmpty()){r.añadiratrib(a);}
           r.añadirent(en2);
           relaciones.add(r);
           relaciones2.add(r);
           String az="";
           for(int x=0;x<r.tamrelacion();x++)
           {
               az=en2.get(x).getnombre()+",";
           }
           cuadro=r.getnombre()+"= "+az+r.getatribr()+r.getcard()+tre+"\n";
        }
        relac.setText("");
        ents.setText("");
        atrib.setText("");
        part.setText("");
        card.setText("");
        tiporelrelacion.setText("");
        textocuadro1 += cuadro;
        EntidadesTexto.setText(textocuadro1);
        
    }//GEN-LAST:event_ingresarrelaActionPerformed

    private void ingresarentcomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresarentcomActionPerformed
        String nombreentc="";
        nombreentc=entcom.getText();
        String entidador="";
        entidador=entorig.getText();
        String atribs="";
        atribs=atribentcom.getText();
        String tipodt="";
        tipodt=tipo.getText();
        String tipoen="";
        tipoen=tipoent2.getText();
        ArrayList<String> atb= new  ArrayList<String>();
        String cuadro="";
        if(nombreentc.equals("") || entidador.equals("") ||  tipodt.equals("") || tipoen.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Necesitas llenar todos los campos minimos", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        else
        {
           if(!atribs.equals("")){
           atb=separador.separarllavespyatrib(atribs);  
           }
           Entidad e= new Entidad(nombreentc,tipoen,entidador,tipodt);
           if(!atb.isEmpty()){e.añadiratrib(atb);}
           entidades.add(e);
           entidades2.add(e);
           cuadro=e.getnombre()+" padre=("+e.getpadre()+"),"+e.getatributos()+"\n";
        }        
        entcom.setText("");
        entorig.setText("");
        atribentcom.setText("");
        tipo.setText("");
        tipoent2.setText("");
        textocuadro1 += cuadro;
        EntidadesTexto.setText(textocuadro1);
    }//GEN-LAST:event_ingresarentcomActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        proceso.agregararrays(entidades, relaciones);
        String finn;
        textocuadro1="";
        proceso.paso1();    
        proceso.paso2(2);
        proceso.paso3();
        proceso.paso4();
        proceso.paso5();
        proceso.paso6();
        proceso.paso7();
        proceso.paso8b();
        finn=proceso.imprimefinal();
        proceso.limpiar();
        proceso2.agregararrays(entidades2, relaciones2);
        String f;
        textocuadro1="";
        proceso2.paso1();    
        proceso2.paso2(2);
        proceso2.paso3();
        proceso2.paso4();
        proceso2.paso5();
        proceso2.paso6();
        proceso2.paso7();
        proceso2.paso8a();
        f=proceso2.imprimefinal();
        proceso2.limpiar();
        JOptionPane.showMessageDialog(null,"Importa si la especializacion es Disyuncion o Traslape:\n"+finn+"\nNo importa si la especializacion es Disyuncion o Traslape:\n"+f, "Transformada", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        entidades.clear();
        relaciones.clear();
        entidades2.clear();
        relaciones2.clear();
        EntidadesTexto.setText("");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void tiporelrelacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tiporelrelacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tiporelrelacionActionPerformed


    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }
    
    private String textocuadro1="";
    private separadortexo separador=new separadortexo();
    private ArrayList<Entidad> entidades2= new ArrayList<Entidad>();
    private ArrayList<Relacion> relaciones2= new ArrayList<Relacion>();
    private ArrayList<Entidad> entidades= new ArrayList<Entidad>();
    private ArrayList<Relacion> relaciones= new ArrayList<Relacion>();
    private Pasos proceso= new Pasos();
    private Pasos proceso2= new Pasos();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea EntidadesTexto;
    private javax.swing.JTextField atrib;
    private javax.swing.JTextField atribcompuesto;
    private javax.swing.JTextField atribentcom;
    private javax.swing.JTextField atribmulti;
    private javax.swing.JTextField atribsimples;
    private javax.swing.JButton botonsalir;
    private javax.swing.JTextField card;
    private javax.swing.JTextField ent;
    private javax.swing.JTextField entcom;
    private javax.swing.JTextField entorig;
    private javax.swing.JTextField ents;
    private javax.swing.JLabel fondo;
    private javax.swing.JButton ingresarent;
    private javax.swing.JButton ingresarentcom;
    private javax.swing.JButton ingresarrela;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField llaveprimaria;
    private javax.swing.JTextField part;
    private javax.swing.JTextField relac;
    private javax.swing.JTextField tipo;
    private javax.swing.JTextField tipodentidad;
    private javax.swing.JTextField tipoent2;
    private javax.swing.JTextField tiporelrelacion;
    // End of variables declaration//GEN-END:variables
}
